"""
Report generation — HTML, JSON, plain text.
"""
from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from scanner.config import REPORTS_DIR
from scanner.utils.output import severity_of

SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high":     "#ea580c",
    "medium":   "#ca8a04",
    "low":      "#16a34a",
    "info":     "#2563eb",
}

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>VulnScan Report — {target}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }}
    h1 {{ font-size: 1.8rem; color: #38bdf8; margin-bottom: 4px; }}
    .meta {{ color: #64748b; font-size: 0.85rem; margin-bottom: 24px; }}
    .stats {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 28px; }}
    .stat {{ background: #1e293b; border-radius: 8px; padding: 14px 20px; min-width: 120px; }}
    .stat-label {{ font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; }}
    .stat-value {{ font-size: 2rem; font-weight: 700; }}
    table {{ width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 8px; overflow: hidden; }}
    th {{ background: #0f172a; color: #94a3b8; text-align: left; padding: 10px 14px; font-size: 0.8rem; text-transform: uppercase; }}
    td {{ padding: 10px 14px; border-top: 1px solid #0f172a; font-size: 0.88rem; word-break: break-all; }}
    tr:hover {{ background: #273549; }}
    .badge {{ display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 0.75rem; font-weight: 700; color: #fff; }}
    .evidence {{ font-family: monospace; background: #0f172a; padding: 4px 8px; border-radius: 4px; font-size: 0.8rem; color: #a3e635; }}
    footer {{ margin-top: 32px; text-align: center; color: #475569; font-size: 0.8rem; }}
  </style>
</head>
<body>
  <h1>VulnScan Report</h1>
  <div class="meta">Target: {target} &nbsp;|&nbsp; Scanned: {timestamp} &nbsp;|&nbsp; Duration: {elapsed}s &nbsp;|&nbsp; URLs crawled: {urls_crawled}</div>
  <div class="stats">
    <div class="stat"><div class="stat-label">Total</div><div class="stat-value" style="color:#38bdf8">{total}</div></div>
    <div class="stat"><div class="stat-label">Critical</div><div class="stat-value" style="color:#dc2626">{critical}</div></div>
    <div class="stat"><div class="stat-label">High</div><div class="stat-value" style="color:#ea580c">{high}</div></div>
    <div class="stat"><div class="stat-label">Medium</div><div class="stat-value" style="color:#ca8a04">{medium}</div></div>
    <div class="stat"><div class="stat-label">Low</div><div class="stat-value" style="color:#16a34a">{low}</div></div>
  </div>
  <table>
    <tr>
      <th>#</th><th>Severity</th><th>Type</th><th>Parameter</th><th>Payload</th><th>URL</th><th>Evidence</th>
    </tr>
    {rows}
  </table>
  <footer>Generated by VulnScan v2.0 &mdash; for authorized security testing only</footer>
</body>
</html>
"""

_ROW_TEMPLATE = """\
    <tr>
      <td>{i}</td>
      <td><span class="badge" style="background:{color}">{severity}</span></td>
      <td><strong>{vtype}</strong></td>
      <td>{param}</td>
      <td class="evidence">{payload}</td>
      <td>{url}</td>
      <td class="evidence">{evidence}</td>
    </tr>
"""


def generate(
    target: str,
    findings: List[Dict[str, Any]],
    urls_crawled: int = 0,
    elapsed: float = 0.0,
    fmt: str = "html",
    output: Path | None = None,
) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    if output is None:
        suffix = {"html": ".html", "json": ".json", "txt": ".txt"}.get(fmt, ".txt")
        output = REPORTS_DIR / f"vulnscan_{ts}{suffix}"

    if fmt == "html":
        content = _html(target, findings, urls_crawled, elapsed, ts)
    elif fmt == "json":
        content = _json(target, findings, urls_crawled, elapsed, ts)
    else:
        content = _text(target, findings, urls_crawled, elapsed, ts)

    output.write_text(content, encoding="utf-8")
    return output


# ── Format builders ────────────────────────────────────────────────────────────

def _counts(findings):
    c = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in findings:
        sev = f.get("severity", severity_of(f.get("type", "")))
        c[sev] = c.get(sev, 0) + 1
    return c


def _html(target, findings, urls_crawled, elapsed, ts) -> str:
    c = _counts(findings)
    rows = ""
    for i, f in enumerate(findings, 1):
        vtype = f.get("type", "?")
        sev   = f.get("severity", severity_of(vtype))
        rows += _ROW_TEMPLATE.format(
            i=i,
            color=SEVERITY_COLORS.get(sev, "#475569"),
            severity=sev.upper(),
            vtype=vtype.upper(),
            param=_esc(f.get("parameter", "N/A")),
            payload=_esc(str(f.get("payload", "N/A"))[:120]),
            url=_esc(f.get("url", "N/A")),
            evidence=_esc(str(f.get("evidence", ""))[:200]),
        )
    return _HTML_TEMPLATE.format(
        target=_esc(target),
        timestamp=ts,
        elapsed=f"{elapsed:.1f}",
        urls_crawled=urls_crawled,
        total=len(findings),
        rows=rows,
        **c,
    )


def _json(target, findings, urls_crawled, elapsed, ts) -> str:
    return json.dumps({
        "target":       target,
        "timestamp":    ts,
        "elapsed":      round(elapsed, 2),
        "urls_crawled": urls_crawled,
        "total":        len(findings),
        "findings":     findings,
    }, indent=2, ensure_ascii=False)


def _text(target, findings, urls_crawled, elapsed, ts) -> str:
    lines = [
        f"VulnScan Report — {target}",
        f"Scanned: {ts}  Duration: {elapsed:.1f}s  URLs: {urls_crawled}",
        "=" * 60,
    ]
    c = _counts(findings)
    lines.append(f"Total: {len(findings)}  " +
                 "  ".join(f"{k.upper()}: {v}" for k, v in c.items()))
    lines.append("")
    for i, f in enumerate(findings, 1):
        vtype = f.get("type", "?")
        sev   = f.get("severity", severity_of(vtype))
        lines += [
            f"[{i}] {sev.upper()} — {vtype.upper()}",
            f"    URL:      {f.get('url', 'N/A')}",
            f"    Param:    {f.get('parameter', 'N/A')}",
            f"    Payload:  {str(f.get('payload','N/A'))[:100]}",
            f"    Evidence: {str(f.get('evidence',''))[:200]}",
            "",
        ]
    return "\n".join(lines)


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;"))
